fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: detect-private-key
      - id: pretty-format-json
        args: ["--autofix", "--indent", "2"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(yaml|yml|md|markdown)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--exclude-files", "node_modules/"]

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c 'cargo fmt -- --check'
        language: rust
        files: \.rs$

      - id: cargo-deny
        name: cargo deny check
        entry: bash -c 'cargo deny check -d'
        language: rust
        files: \.rs$

      - id: cargo-audit
        name: cargo audit
        entry: bash -c 'cargo audit'
        language: rust
        files: \.rs$
        pass_filenames: false

      - id: cargo-outdated
        name: cargo outdated
        entry: bash -c 'cargo outdated --exit-code 1'
        language: rust
        files: \.rs$
        pass_filenames: false

      - id: typos
        name: typos
        entry: bash -c 'typos'
        language: rust
        files: .*$
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        entry: bash -c 'cargo check --all'
        language: rust
        files: \.rs$
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: bash -c 'cargo clippy --all-targets --all-features --tests --benches -- -D warnings'
        language: rust
        files: \.rs$
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        entry: bash -c 'cargo nextest run --all-features'
        language: rust
        files: \.rs$
        pass_filenames: false
